version: 2

jobs:

  test:
    working_directory: ~/repo
    environment:
      MOCHA_FILE: test-results/mocha/test-results.xml
    docker:
      - image: circleci/node:17
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: build
          command: yarn
      - run:
          name: test
          command: yarn test


  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:17
    steps:
      - checkout
      - attach_workspace:
          at: .
      - deploy:
          name: publish
          command: |
            echo -e "$NPM_USERNAME\n$NPM_PASSWORD\n$NPM_EMAIL" | npm login
            npm run publish-if-version-changed

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
