version: 2

defaults: &defaults
  resource_class: large
  docker:
    - image: cimg/node:16.16
  working_directory: ~/repo

jobs:
  test:
    <<: *defaults
    environment:
      MOCHA_FILE: test-results/mocha/test-results.xml
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: build
          command: yarn
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: test
          command: yarn test

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - deploy:
          name: publish
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN" >> ~/.npmrc
            npm publish --access public

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          context:
            - retracedhq
          filters:
            branches:
              only:
                - release
