version: 2

defaults: &defaults
  resource_class: large
  docker:
    - image: cimg/node:16.16

jobs:
  test:
    <<: *defaults
    environment:
      MOCHA_FILE: test-results/mocha/test-results.xml
    steps:
      - checkout
      - run:
          name: build
          command: yarn install
      - run:
          name: test
          command: yarn test

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Yarn
          command: "yarn install"
      - run:
          name: publish
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN" >> ~/.npmrc
            npm publish --access public

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          context:
            - retracedhq
          filters:
            branches:
              only: release
